spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/pdp
    username: postgres
    password: password
  liquibase:
    enabled: true
    change-log: classpath:liquibase/changelog-master.yml
    url: jdbc:postgresql://localhost:5432/pdp
    user: postgres
    password: password
  mail:
    host: smtp.gmail.com
    username: ${EMAIL_USER}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    port: 587

server:
  error:
    include-message: always

logging:
  level:
    org.springframework.r2dbc: debug

client-app:
  base-link: http://localhost:3000

jwt:
  secret: "Jwt secret key"
  expiration-in-ms: 604800000
